### ISSUE TITLE
Python support please?

### ISSUE THREAD

**Issue by JeldorPKU** [DemonCloud/J#1]
:smiley:

**Comment by DemonCloud** [comment]
@JeldorPKU 
Yeah . I will do this ~

**Comment by JeldorPKU** [comment]
Thank you very much! Looking forward to that, @DemonCloud :laughing:

**Comment by DemonCloud** [comment]
@JeldorPKU 

add python support! :smile:  :hamster:
please update colorscheme
![screenshot from 2015-07-31 12-37-34](https://cloud.githubusercontent.com/assets/7436361/9000359/126aaac0-3781-11e5-8c1d-b5e1a6708c54.png)

![screenshot from 2015-07-31 12-37-54](https://cloud.githubusercontent.com/assets/7436361/9000361/149aeba2-3781-11e5-8b7d-9e260f40d34b.png)

I suggest you using `kh3phr3n/python-syntax` python syntax plugin, if you have more amazing Python syntax plugin, please tell me. I will add support in J colorscheme

https://github.com/kh3phr3n/python-syntax

and add it to your vimrc:
`let python_self_cls_highlight = 1`

**Comment by JeldorPKU** [comment]
I see it, thank you very much!
